### ISSUE TITLE
Expose gists "public" attribute to allow secret gists

### ISSUE THREAD

**Issue by Unode** [zlin/wgetpaste#2]
Hi Bo,

I'd like to be able to default to secret gists when using the github service.
I see in the API docs that "public:false" is the default and I also see in wgetpaste that "public: true" is hardcoded in the gist JSON request. Is there any way this could be exposed so I could customize it from a config file?

Thanks

**Comment by zlin** [comment]
I'd certainly take a patch.

I guess the most simplistic would be making it use public: ${PUBLIC_gists:-true}. Or you can suggest something more sophisticated.

**Comment by Unode** [comment]
Took a while :)

https://gist.github.com/Unode/7e65f53bb152485d038b

Uploaded using the patch itself.

**Comment by zlin** [comment]
I clearly haven't quite understood this commenting system...

> Took a while :)

Yeah, I'm finally caught up on reading mails again. ;)

If I should fall behind again, IRC on freenode will probably remain the quickest way to gain my attention.

> https://gist.github.com/Unode/7e65f53bb152485d038b

Please use [[ ... || .. ]] rather than [[ ... ]] || [[ ... ]] on line 38.

Looks good otherwise.

**Comment by Unode** [comment]
Updated.

**Comment by zlin** [comment]
Alright, it's in version 2.27

**Comment by Unode** [comment]
Cool, cheers
